### ISSUE TITLE
now u cant use jetpack

### ISSUE THREAD

**Issue by Pryan1kk** [ButteryStancakes/JetpackFixes#1]
jetpack fixes crashing jetpack wow
![image](https://github.com/ButteryStancakes/JetpackFixes/assets/170948343/1f45f3df-eed4-4d8f-bf50-9961feced20f)

**Comment by ChimpD** [comment]
Having only a cursory grasp of the code, i think the problem stems from this change:
From       static void PreJetpackUpdate(JetpackItem __instance, Vector3 ___forces, bool ___jetpackActivated, float ___jetpackPower)
To            static void PreJetpackUpdate(JetpackItem __instance, **ref** Vector3 ___forces, bool ___jetpackActivated, float ___jetpackPower)

In both the csproj and the plugin.cs

**Comment by ButteryStancakes** [comment]
When I updated this plugin, I made the mistake of using the v55 assemblies, which changes the signature of `PlayerControllerB.KillPlayer` and causes it to break my Update() patch if you are using it in v50. I will roll this change back in v1.2.1 until the next update is out of public beta.

(Unfortunately, this will have the opposite result of breaking jetpacks in v56...)
